# Generated by Django 4.2.4 on 2023-08-31 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='device_parameter_id',
            new_name='device',
        ),
    ]
