# Generated by Django 4.2.4 on 2023-12-27 14:05

import app1.models
from django.db import migrations, models
import django.db.models.aggregates
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_name', models.CharField(max_length=100)),
                ('Account_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('user_category', models.CharField(choices=[('3d', '3D PRINTING'), ('aqua', 'AQUA CULTURE'), ('water', 'WATER BODY MANAGEMENT')], default=(('3d', '3D PRINTING'), ('aqua', 'AQUA CULTURE'), ('water', 'WATER BODY MANAGEMENT')), max_length=20)),
                ('user_img', models.ImageField(blank=True, upload_to=app1.models.admin_img)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=24)),
                ('version', models.IntegerField()),
                ('controls', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Adhaar', models.IntegerField()),
                ('account_name', models.CharField(max_length=50)),
                ('device_details', models.CharField(max_length=200)),
                ('user_category', models.CharField(choices=[('3d', '3D PRINTING'), ('aqua', 'AQUA CULTURE'), ('water', 'WATER BODY MANAGEMENT')], default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('Adhaar', models.IntegerField()),
                ('user_pic', models.ImageField(blank=True, upload_to='user_img/')),
                ('user_docs', models.FileField(blank=True, upload_to='user_docs/')),
                ('user_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.adminuser')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='app1.account')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.aggregates.Aggregate, related_name='device_type', to='app1.devicetype')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_type', models.CharField(max_length=100)),
                ('param_value', models.JSONField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.device')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='app1.user'),
        ),
    ]
