# Generated by Django 4.2.4 on 2023-12-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='device_details',
        ),
        migrations.AddField(
            model_name='registration',
            name='params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='Account_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='version',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Adhaar',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='Adhaar',
            field=models.BigIntegerField(),
        ),
    ]
