# Generated by Django 4.2.4 on 2023-08-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_permission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='CustomPermission',
        ),
    ]
