# Generated by Django 4.2.4 on 2023-12-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_registration_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
