# Generated by Django 4.2.4 on 2023-08-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_device_parameter_id_parameter_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqtt_device',
            name='device_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
