# Generated by Django 4.2.4 on 2023-12-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='token',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
